//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserFootballTotal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder05"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder05"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder05"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder25"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder25"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder25"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAllFailedToScore"]));
            }
            set {
                this["settingAllMatchInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeFailedToScore {
            get {
                return ((int)(this["settingAllMatchInHomeFailedToScore"]));
            }
            set {
                this["settingAllMatchInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAwayFailedToScore"]));
            }
            set {
                this["settingAllMatchInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAllFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInHomeFailedToScore"]));
            }
            set {
                this["settingFirstTimeInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAwayFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAllFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInHomeFailedToScore"]));
            }
            set {
                this["settingSecondTimeInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAwayFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder15"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder15"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder15"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllCleanSheets {
            get {
                return ((int)(this["settingAllMatchInAllCleanSheets"]));
            }
            set {
                this["settingAllMatchInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeCleanSheets {
            get {
                return ((int)(this["settingAllMatchInHomeCleanSheets"]));
            }
            set {
                this["settingAllMatchInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayCleanSheets {
            get {
                return ((int)(this["settingAllMatchInAwayCleanSheets"]));
            }
            set {
                this["settingAllMatchInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInAllCleanSheets"]));
            }
            set {
                this["settingFirstTimeInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInHomeCleanSheets"]));
            }
            set {
                this["settingFirstTimeInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInAwayCleanSheets"]));
            }
            set {
                this["settingFirstTimeInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInAllCleanSheets"]));
            }
            set {
                this["settingSecondTimeInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInHomeCleanSheets"]));
            }
            set {
                this["settingSecondTimeInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInAwayCleanSheets"]));
            }
            set {
                this["settingSecondTimeInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAllBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInHomeBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAwayBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInAwayBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAllBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInHomeBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAwayBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAwayBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAllBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInHomeBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAwayBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAwayBothFailedToScore"] = value;
            }
        }
        
                   [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllTotalUnder05"]));
                }
                set
                {
                    this["cbAllMatchInAllTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeTotalUnder05"]));
                }
                set
                {
                    this["cbAllMatchInHomeTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayTotalUnder05"]));
                }
                set
                {
                    this["cbAllMatchInAwayTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllTotalUnder25"]));
                }
                set
                {
                    this["cbAllMatchInAllTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeTotalUnder25"]));
                }
                set
                {
                    this["cbAllMatchInHomeTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayTotalUnder25"]));
                }
                set
                {
                    this["cbAllMatchInAwayTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInAllFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInHomeFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInAwayFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllTotalUnder05"]));
                }
                set
                {
                    this["cbFirstTimeInAllTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeTotalUnder05"]));
                }
                set
                {
                    this["cbFirstTimeInHomeTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayTotalUnder05"]));
                }
                set
                {
                    this["cbFirstTimeInAwayTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllTotalUnder25"]));
                }
                set
                {
                    this["cbFirstTimeInAllTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeTotalUnder25"]));
                }
                set
                {
                    this["cbFirstTimeInHomeTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayTotalUnder25"]));
                }
                set
                {
                    this["cbFirstTimeInAwayTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInAllFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInHomeFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInAwayFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllTotalUnder05"]));
                }
                set
                {
                    this["cbSecondTimeInAllTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeTotalUnder05"]));
                }
                set
                {
                    this["cbSecondTimeInHomeTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayTotalUnder05
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayTotalUnder05"]));
                }
                set
                {
                    this["cbSecondTimeInAwayTotalUnder05"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllTotalUnder25"]));
                }
                set
                {
                    this["cbSecondTimeInAllTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeTotalUnder25"]));
                }
                set
                {
                    this["cbSecondTimeInHomeTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayTotalUnder25
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayTotalUnder25"]));
                }
                set
                {
                    this["cbSecondTimeInAwayTotalUnder25"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInAllFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInHomeFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInAwayFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllTotalUnder15"]));
                }
                set
                {
                    this["cbAllMatchInAllTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeTotalUnder15"]));
                }
                set
                {
                    this["cbAllMatchInHomeTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayTotalUnder15"]));
                }
                set
                {
                    this["cbAllMatchInAwayTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllCleanSheets
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllCleanSheets"]));
                }
                set
                {
                    this["cbAllMatchInAllCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeCleanSheets
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeCleanSheets"]));
                }
                set
                {
                    this["cbAllMatchInHomeCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayCleanSheets
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayCleanSheets"]));
                }
                set
                {
                    this["cbAllMatchInAwayCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllTotalUnder15"]));
                }
                set
                {
                    this["cbFirstTimeInAllTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeTotalUnder15"]));
                }
                set
                {
                    this["cbFirstTimeInHomeTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayTotalUnder15"]));
                }
                set
                {
                    this["cbFirstTimeInAwayTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllCleanSheets
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllCleanSheets"]));
                }
                set
                {
                    this["cbFirstTimeInAllCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeCleanSheets
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeCleanSheets"]));
                }
                set
                {
                    this["cbFirstTimeInHomeCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayCleanSheets
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayCleanSheets"]));
                }
                set
                {
                    this["cbFirstTimeInAwayCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllTotalUnder15"]));
                }
                set
                {
                    this["cbSecondTimeInAllTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeTotalUnder15"]));
                }
                set
                {
                    this["cbSecondTimeInHomeTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayTotalUnder15
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayTotalUnder15"]));
                }
                set
                {
                    this["cbSecondTimeInAwayTotalUnder15"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllCleanSheets
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllCleanSheets"]));
                }
                set
                {
                    this["cbSecondTimeInAllCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeCleanSheets
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeCleanSheets"]));
                }
                set
                {
                    this["cbSecondTimeInHomeCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayCleanSheets
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayCleanSheets"]));
                }
                set
                {
                    this["cbSecondTimeInAwayCleanSheets"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAllBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAllBothFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInAllBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInHomeBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInHomeBothFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInHomeBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbAllMatchInAwayBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbAllMatchInAwayBothFailedToScore"]));
                }
                set
                {
                    this["cbAllMatchInAwayBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAllBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAllBothFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInAllBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInHomeBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInHomeBothFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInHomeBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbFirstTimeInAwayBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbFirstTimeInAwayBothFailedToScore"]));
                }
                set
                {
                    this["cbFirstTimeInAwayBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAllBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAllBothFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInAllBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInHomeBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInHomeBothFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInHomeBothFailedToScore"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool cbSecondTimeInAwayBothFailedToScore
            {
                get
                {
                    return ((bool)(this["cbSecondTimeInAwayBothFailedToScore"]));
                }
                set
                {
                    this["cbSecondTimeInAwayBothFailedToScore"] = value;
                }
            }

        }
}
