//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParserFootballTotal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder05"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder05"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder05 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder05"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder25"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder25"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder25 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder25"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAllFailedToScore"]));
            }
            set {
                this["settingAllMatchInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeFailedToScore {
            get {
                return ((int)(this["settingAllMatchInHomeFailedToScore"]));
            }
            set {
                this["settingAllMatchInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAwayFailedToScore"]));
            }
            set {
                this["settingAllMatchInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder05 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder05"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder25 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder25"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAllFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInHomeFailedToScore"]));
            }
            set {
                this["settingFirstTimeInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAwayFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder05 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder05"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder25 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder25"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAllFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAllFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInHomeFailedToScore"]));
            }
            set {
                this["settingSecondTimeInHomeFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAwayFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAwayFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInAllTotalUnder15"]));
            }
            set {
                this["settingAllMatchInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInHomeTotalUnder15"]));
            }
            set {
                this["settingAllMatchInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayTotalUnder15 {
            get {
                return ((int)(this["settingAllMatchInAwayTotalUnder15"]));
            }
            set {
                this["settingAllMatchInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllCleanSheets {
            get {
                return ((int)(this["settingAllMatchInAllCleanSheets"]));
            }
            set {
                this["settingAllMatchInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeCleanSheets {
            get {
                return ((int)(this["settingAllMatchInHomeCleanSheets"]));
            }
            set {
                this["settingAllMatchInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayCleanSheets {
            get {
                return ((int)(this["settingAllMatchInAwayCleanSheets"]));
            }
            set {
                this["settingAllMatchInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInAllTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInHomeTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayTotalUnder15 {
            get {
                return ((int)(this["settingFirstTimeInAwayTotalUnder15"]));
            }
            set {
                this["settingFirstTimeInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInAllCleanSheets"]));
            }
            set {
                this["settingFirstTimeInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInHomeCleanSheets"]));
            }
            set {
                this["settingFirstTimeInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayCleanSheets {
            get {
                return ((int)(this["settingFirstTimeInAwayCleanSheets"]));
            }
            set {
                this["settingFirstTimeInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInAllTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInAllTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInHomeTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInHomeTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayTotalUnder15 {
            get {
                return ((int)(this["settingSecondTimeInAwayTotalUnder15"]));
            }
            set {
                this["settingSecondTimeInAwayTotalUnder15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInAllCleanSheets"]));
            }
            set {
                this["settingSecondTimeInAllCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInHomeCleanSheets"]));
            }
            set {
                this["settingSecondTimeInHomeCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayCleanSheets {
            get {
                return ((int)(this["settingSecondTimeInAwayCleanSheets"]));
            }
            set {
                this["settingSecondTimeInAwayCleanSheets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAllBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAllBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInHomeBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInHomeBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingAllMatchInAwayBothFailedToScore {
            get {
                return ((int)(this["settingAllMatchInAwayBothFailedToScore"]));
            }
            set {
                this["settingAllMatchInAwayBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAllBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAllBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInHomeBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInHomeBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingFirstTimeInAwayBothFailedToScore {
            get {
                return ((int)(this["settingFirstTimeInAwayBothFailedToScore"]));
            }
            set {
                this["settingFirstTimeInAwayBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAllBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAllBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAllBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInHomeBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInHomeBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInHomeBothFailedToScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int settingSecondTimeInAwayBothFailedToScore {
            get {
                return ((int)(this["settingSecondTimeInAwayBothFailedToScore"]));
            }
            set {
                this["settingSecondTimeInAwayBothFailedToScore"] = value;
            }
        }
    }
}
